inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/*'
    - 'demo.rb'
    - 'test/blocks_test.rb'


Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
